### ISSUE TITLE
Adicionar templates de pull request para o repositório

### ISSUE THREAD

**Issue by frattezi** [Joel-leal/voting-system#9]
Utilizando a doc do [github sobre criação de templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) crie um novo PR template para o repo.

Pesquise sobre um formato que você ache interessante, não se acanhe, podemos fazer discussões sobre o template no review.

Dicas:
- Utilize Markdown
- Tópicos sugeridos: Por que este PR é necessário; O que foi feito; Condições de aceite; Demonstração visual
- Exemplo [PodCodar WebApp](https://github.com/podcodar/webapp/blob/main/.github/pull_request_template.md)

**Comment by fmagesty** [comment]
![Image](https://user-images.githubusercontent.com/28074722/175432584-754dee92-d683-4596-93f8-0ac661b20d93.png)

**Comment by fmagesty** [comment]
update: fiz algumas leves mudanças baseadas no webapp e também os PRs mais recentes daqui do voting system que incluem o número do PR aí da pra clicar nele e ir direto pra página da tarefa. Me digam o que acham se está bom assim. O próximo passo é fazer com que essa template seja gerada automaticamente no deploy mas tenho ainda que ver como configurar isso porque nunca o fiz. Segue imagem das mudanças abaixo





![Image](https://user-images.githubusercontent.com/28074722/175516166-59c41187-9a64-4321-8c9f-75b30b9facb6.png)
